# Generated by Django 4.2.2 on 2023-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('POST', 'User created a post'), ('DELETE', 'User deleted a post'), ('BANNED', 'User banned a user'), ('UNBANNED', 'User unbanned a user')], max_length=12),
        ),
    ]
